USE APP_WORK 
GO

IF  OBJECT_ID('APP_WORK..EDI_XC_PROV_NPI_REJECTED_CLAIMS') IS NOT NULL
	BEGIN
		DROP TABLE APP_WORK..EDI_XC_PROV_NPI_REJECTED_CLAIMS
   		PRINT '<< TABLE [APP_WORK..EDI_XC_PROV_NPI_REJECTED_CLAIMS] Dropped >>'
   	END
ELSE 	
	PRINT '<< TABLE [APP_WORK..EDI_XC_PROV_NPI_REJECTED_CLAIMS] DOES NOT EXIST >>'   	
GO

/*********************************************************************************
	NAME:			APP_WORK..EDI_XC_PROV_NPI_REJECTED_CLAIMS							
	DESCRIPTION:    TABLE TO STAGE XC CLAIM REJECTION DELETES FOR FACETS SP
	DEVELOPER:      FRANK P. RUNFOLA
	DATE:			5/22/2019
*********************************************************************************/

CREATE TABLE APP_WORK..EDI_XC_PROV_NPI_REJECTED_CLAIMS
(
	  CLCL_ID           CHAR (12) 	 	NOT NULL
	, CLCL_CL_SUB_TYPE  CHAR (1)  	 	NOT NULL
	, CREATED_BY        VARCHAR (20)	NOT NULL
	, CREATED_DATE      DATETIME  		NOT NULL
	, CLCL_BATCH_ID     CHAR (8)  		NULL
	, CLED_EXT_REF      CHAR (40)  		NULL
	, CLCL_CUR_STS      CHAR (3)  		NULL
	, CLCL_INPUT_DT     DATETIME  		NULL
	, CLCL_TOT_CHG      MONEY  			NULL
	, DBASE             VARCHAR (6)		NULL
	, CLED_TRAD_PARTNER CHAR (15)  		NULL
	, SYS_DT            DATETIME   		NULL
	, LAST_NAME         CHAR (35)  		NULL
	, FIRST_NAME        CHAR (15)  		NULL
	, FROM_DT           DATETIME  		NULL
	, TO_DT             DATETIME  		NULL
	, CLCL_PA_ACCT_NO   VARCHAR (35)  	NULL
	, SBSB_ID           CHAR (15)  		NULL
	, MCTN_ID           CHAR (9)  		NULL
	, PRPR_NPI          CHAR (10)  		NULL
	, PRPR_NAME         VARCHAR (55)  	NULL
	)
GO

CREATE UNIQUE CLUSTERED INDEX UX_EDI_XC_PROV_NPI_REJECTED_CLAIMS_CLCL_ID ON APP_WORK..EDI_XC_PROV_NPI_REJECTED_CLAIMS (CLCL_ID) ON 'default'
GO

GRANT INSERT, SELECT, DELETE, UPDATE ON APP_WORK..EDI_XC_PROV_NPI_REJECTED_CLAIMS TO Claims_Rejection_Role
GO

IF  OBJECT_ID('APP_WORK..EDI_XC_PROV_NPI_REJECTED_CLAIMS') IS NOT NULL
   	PRINT '<< TABLE [APP_WORK..EDI_XC_PROV_NPI_REJECTED_CLAIMS] CREATED! >>'

--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

USE APP_WORK 
GO

IF  OBJECT_ID('APP_WORK..EDI_XC_PROV_NAME_REJECTED_CLAIMS') IS NOT NULL
	BEGIN
		DROP TABLE APP_WORK..EDI_XC_PROV_NAME_REJECTED_CLAIMS
   		PRINT '<< TABLE [APP_WORK..EDI_XC_PROV_NAME_REJECTED_CLAIMS] Dropped >>'
   	END
ELSE 	
	PRINT '<< TABLE [APP_WORK..EDI_XC_PROV_NAME_REJECTED_CLAIMS] DOES NOT EXIST >>'   	
GO

/*********************************************************************************
	NAME:			APP_WORK..EDI_XC_PROV_NAME_REJECTED_CLAIMS							
	DESCRIPTION:    TABLE TO STAGE XC CLAIM REJECTION DELETES FOR FACETS SP
	DEVELOPER:      FRANK P. RUNFOLA
	DATE:			5/22/2019
*********************************************************************************/
CREATE TABLE APP_WORK..EDI_XC_PROV_NAME_REJECTED_CLAIMS
	(
	  CLCL_ID           CHAR (12) NOT NULL
	, CLCL_CL_SUB_TYPE  CHAR (1)  NOT NULL
	, CREATED_BY        VARCHAR (20) NOT NULL
	, CREATED_DATE      DATETIME  NOT NULL
	, CLCL_BATCH_ID     CHAR (8)  NULL
	, CLED_EXT_REF      CHAR (40)  NULL
	, CLCL_CUR_STS      CHAR (3)  NULL
	, CLCL_INPUT_DT     DATETIME  NULL
	, CLCL_TOT_CHG      MONEY  NULL
	, DBASE             VARCHAR (6)  NULL
	, CLED_TRAD_PARTNER CHAR (15)  NULL
	, SYS_DT            DATETIME  NULL
	, LAST_NAME         CHAR (35)  NULL
	, FIRST_NAME        CHAR (15)  NULL
	, FROM_DT           DATETIME  NULL
	, TO_DT             DATETIME  NULL
	, CLCL_PA_ACCT_NO   VARCHAR (35)  NULL
	, SBSB_ID           CHAR (15)  NULL
	, MCTN_ID           CHAR (9)  NULL
	, PRPR_NPI          CHAR (10)  NULL
	, PRPR_NAME         VARCHAR (55)  NULL
	)
GO

CREATE UNIQUE CLUSTERED INDEX UX_EDI_XC_PROV_NAME_REJECTED_CLAIMS_CLCL_ID ON APP_WORK..EDI_XC_PROV_NAME_REJECTED_CLAIMS (CLCL_ID) ON 'default'
GO

GRANT INSERT, SELECT, DELETE, UPDATE ON APP_WORK..EDI_XC_PROV_NAME_REJECTED_CLAIMS TO Claims_Rejection_Role
GO

IF  OBJECT_ID('APP_WORK..EDI_XC_PROV_NAME_REJECTED_CLAIMS') IS NOT NULL
   	PRINT '<< TABLE [APP_WORK..EDI_XC_PROV_NAME_REJECTED_CLAIMS] CREATED! >>'

--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
USE APP_WORK 
GO

IF  OBJECT_ID('APP_WORK..EDI_XC_PROV_TIN_REJECTED_CLAIMS') IS NOT NULL
	BEGIN
		DROP TABLE APP_WORK..EDI_XC_PROV_TIN_REJECTED_CLAIMS
   		PRINT '<< TABLE [APP_WORK..EDI_XC_PROV_TIN_REJECTED_CLAIMS] Dropped >>'
   	END
ELSE 	
	PRINT '<< TABLE [APP_WORK..EDI_XC_PROV_TIN_REJECTED_CLAIMS] DOES NOT EXIST >>'   	
GO

/*********************************************************************************
	NAME:			APP_WORK..EDI_XC_PROV_TIN_REJECTED_CLAIMS							
	DESCRIPTION:    TABLE TO STAGE XC CLAIM REJECTION DELETES FOR FACETS SP
	DEVELOPER:      FRANK P. RUNFOLA
	DATE:			5/22/2019
*********************************************************************************/

CREATE TABLE APP_WORK..EDI_XC_PROV_TIN_REJECTED_CLAIMS
	(
	  CLCL_ID           CHAR (12) NOT NULL
	, CLCL_CL_SUB_TYPE  CHAR (1) NOT NULL
	, CREATED_BY        VARCHAR (20) NOT NULL
	, CREATED_DATE      DATETIME NOT NULL
	, CLCL_BATCH_ID     CHAR (8)  NULL
	, CLED_EXT_REF      CHAR (40)  NULL
	, CLCL_CUR_STS      CHAR (3)  NULL
	, CLCL_INPUT_DT     DATETIME  NULL
	, CLCL_TOT_CHG      MONEY  NULL
	, DBASE             VARCHAR (6)  NULL
	, CLED_TRAD_PARTNER CHAR (15)  NULL
	, SYS_DT            DATETIME  NULL
	, LAST_NAME         CHAR (35)  NULL
	, FIRST_NAME        CHAR (15)  NULL
	, FROM_DT           DATETIME  NULL
	, TO_DT             DATETIME  NULL
	, CLCL_PA_ACCT_NO   VARCHAR (35)  NULL
	, SBSB_ID           CHAR (15)  NULL
	, MCTN_ID           CHAR (9)  NULL
	, PRPR_NPI          CHAR (10)  NULL
	, PRPR_NAME         VARCHAR (55)  NULL
	)
GO

CREATE UNIQUE CLUSTERED INDEX UX_EDI_XC_PROV_TIN_REJECTED_CLAIMS_CLCL_ID ON APP_WORK..EDI_XC_PROV_TIN_REJECTED_CLAIMS (CLCL_ID) ON 'default'
GO

GRANT INSERT, SELECT, DELETE, UPDATE  ON APP_WORK..EDI_XC_PROV_TIN_REJECTED_CLAIMS TO Claims_Rejection_Role
GO

IF  OBJECT_ID('APP_WORK..EDI_XC_PROV_TIN_REJECTED_CLAIMS') IS NOT NULL
   	PRINT '<< TABLE [APP_WORK..EDI_XC_PROV_TIN_REJECTED_CLAIMS] CREATED! >>'